Trivy ci/cd changes

diff --git a/.github/workflows/pr-workflow.yaml b/.github/workflows/pr-workflow.yaml
--- a/.github/workflows/pr-workflow.yaml
+++ b/.github/workflows/pr-workflow.yaml
@@ -5,9 +5,6 @@ on:
     branches:
       - main
 
-env:
-  DOCKER_REGISTRY: ghcr.io
-  IMAGE_NAME: ${{ github.repository }}
 
 jobs:
 
@@ -57,6 +54,9 @@ jobs:
     name: Build, scan and publish docker image
     needs: [test-run,filesystem-scan]
     runs-on: ubuntu-latest
+    env:
+      DOCKER_REGISTRY: ghcr.io
+      DOCKER_REPOSITORY: ${{ github.repository }}
     steps:
       - uses: actions/checkout@v3
       - uses: actions/setup-java@v3
@@ -89,24 +89,26 @@ jobs:
           password: ${{ secrets.GITHUB_TOKEN }}
       - name: Set envs
         run: |
-          echo "DOCKER_IMAGE_NAME_WITH_TAG=`echo $(docker images --format "{{.Repository}}:{{.Tag}}" | grep -m1 ${{env.IMAGE_NAME}})`" >> $GITHUB_ENV
-      - name: Scan image with Trivy
-        uses: aquasecurity/trivy-action@master
-        with:
-          scan-type: image
-          image-ref: ${{env.DOCKER_IMAGE_NAME_WITH_TAG}}
-          format: 'sarif'
-          output: 'trivy-image-scan-results.sarif'
-          exit-code: '1'
-          ignore-unfixed: true
-          severity: 'MEDIUM,HIGH,CRITICAL'
-      - name: Upload scan results to GitHub Security tab
-        uses: github/codeql-action/upload-sarif@v2
-        if: success() || failure()
-        with:
-          sarif_file: 'trivy-image-scan-results.sarif'
+          echo "IMAGE_NAME=`echo $(docker images --format "{{.Repository}}:{{.Tag}}" | grep -m1 ${{env.IMAGE_NAME}})`" >> $GITHUB_ENV
+      - name: Test
+        run:
+          env
+#      - name: Scan image with Trivy
+#        uses: aquasecurity/trivy-action@master
+#        with:
+#          scan-type: image
+#          image-ref: ${{env.DOCKER_IMAGE_NAME_WITH_TAG}}
+#          format: 'sarif'
+#          output: 'trivy-image-scan-results.sarif'
+#          exit-code: '1'
+#          ignore-unfixed: true
+#          severity: 'MEDIUM,HIGH,CRITICAL'
+#      - name: Upload scan results to GitHub Security tab
+#        uses: github/codeql-action/upload-sarif@v2
+#        if: success() || failure()
+#        with:
+#          sarif_file: 'trivy-image-scan-results.sarif'
       - name: Publish image
         run: |
-          image=$(docker images --format "{{.Repository}}" | grep -m1 ${{env.DOCKER_REGISTRY}})
-          echo image $image
-          docker push --all-tags $image
+          echo $IMAGE_NAME
+          docker push --all-tags $IMAGE_NAME
